package com.old.silence.auth.center.domain.model;


import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;

import java.math.BigInteger;
import java.util.Set;


@TableName("sys_role")
public class Role extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger, Boolean> {

    /**
     * 角色名称
     */
    private String name;

    /**
     * 角色编码
     */
    private String code;

    /**
     * 角色所属应用编码
     */
    private String appCode;

    /**
     * 角色描述
     */
    private String description;

    /**
     * 状态：0-禁用，1-启用
     */
    private Boolean status;

    @TableField(exist = false)
    private Set<BigInteger> menuIds;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getAppCode() {
        return appCode;
    }

    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Set<BigInteger> getMenuIds() {
        return menuIds;
    }

    public void setMenuIds(Set<BigInteger> menuIds) {
        this.menuIds = menuIds;
    }
}