package com.old.silence.auth.center.domain.model;


import java.math.BigInteger;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdLogicalDeletionAuditable;


@TableName("sys_role_menu")
public class RoleMenu extends AbstractAutoGeneratedIdLogicalDeletionAuditable<BigInteger, Boolean> {

    /**
     * 角色ID
     */
    private BigInteger roleId;

    /**
     * 菜单ID
     */
    private BigInteger menuId;

    public RoleMenu() {
    }

    public RoleMenu(BigInteger roleId, BigInteger menuId) {
        this.roleId = roleId;
        this.menuId = menuId;
    }

    public BigInteger getRoleId() {
        return roleId;
    }

    public void setRoleId(BigInteger roleId) {
        this.roleId = roleId;
    }

    public BigInteger getMenuId() {
        return menuId;
    }

    public void setMenuId(BigInteger menuId) {
        this.menuId = menuId;
    }
}