package com.old.silence.auth.center.domain.model;


import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

@TableName("sys_user_role")
public class UserRole extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    /**
     * 用户ID
     */
    private BigInteger userId;

    /**
     * 角色ID
     */
    private BigInteger roleId;

    public BigInteger getUserId() {
        return userId;
    }

    public void setUserId(BigInteger userId) {
        this.userId = userId;
    }

    public BigInteger getRoleId() {
        return roleId;
    }

    public void setRoleId(BigInteger roleId) {
        this.roleId = roleId;
    }
}